export const USER_REGISTER = "USER_REGISTER"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"

export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const GET_PROFILE = "USER_PROFILE"
export const GET_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const GET_PROFILE_FAILED = "USER_PROFILE_FAILED"

export const VET_REGISTER = "VET_REGISTER"
export const VET_REGISTER_SUCCESS = "VET_REGISTER_SUCCESS"
export const VET_REGISTER_FAILED = "VET_REGISTER_FAILED"

export const LOGOUT = "LOGOUT"


export const GET_VET = "GET_VET"